routes/admin.php
<?php
/**
 * ${NAME}
 * Copyright (C) Marcel Pfeifer 2021 <webmaster@m-pfeifer.de>
 * Date: 04.01.2021
 * Time: 19:39
 *
 *    ___
 * __/_  `.  .-"""-.
 * \_,` | \-'  /   )`-')
 *  "") `"`    \  ((`"`
 *  ___Y  ,    .'7 /|
 * (_,___/...-` (_/_/
 */

Route::namespace('Admin')->middleware(
    ['permission:' . \App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND, 'auth']
)->prefix('admin')->name('admin.')->group(
    function () {
        Route::get('', 'AdminController@index')->name('index');
        Route::namespace('Player')->prefix('player')->name('player.')->middleware(
            'permission:' . \App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_PLAYER
        )->group(
            function () {
                Route::get('/', 'IndexController@index')->name('index');
                Route::get('edit/{userId}', 'IndexController@edit')->name('edit');
                Route::post('/save/{userId}', 'IndexController@save')->name('save');

                Route::get('/releaseFromPrison/{userId}', 'IndexController@releaseFromPrison')
                    ->name('releaseFromPrison')
                    ->middleware(
                        'permission:' . \App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_PLAYER_EDIT_PRISON
                    );
                Route::get('/resetDimension/{userId}', 'IndexController@resetDimension')
                    ->name('resetDimension')
                    ->middleware(
                        'permission:' . \App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_PLAYER_EDIT_DIMENSION
                    );
                Route::get('/deleteFactionLocker/{userId}', 'IndexController@deleteFactionLocker')
                    ->name('deleteFactionLocker')
                    ->middleware(
                        'permission:' . \App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_PLAYER_EDIT_DELETE_PLAYER_LOCKER
                    );
                Route::get('/deleteFactionLockerWeapon/{userId}', 'IndexController@deleteFactionLockerWeapon')
                    ->name('deleteFactionLockerWeapon')
                    ->middleware(
                        'permission:' . \App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_PLAYER_EDIT_DELETE_PLAYER_LOCKER
                    );
                Route::get('/playerResetPosition/{userId}', 'IndexController@playerResetPosition')
                    ->name('resetPosition')
                    ->middleware(
                        'permission:' . \App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_PLAYER_EDIT_PLAYER_POSITION_RESET
                    );
                Route::get('/playerReset/{userId}', 'IndexController@playerReset')
                    ->name('reset')
                    ->middleware(
                        'permission:' . \App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_PLAYER_EDIT_PLAYER_RESET
                    );

                Route::get('/inventoryReset/{userId}', 'IndexController@inventoryReset')
                    ->name('inventoryReset')
                    ->middleware(
                        'permission:' . \App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_PLAYER_EDIT_PLAYER_INVENTORY_RESET
                    );

                Route::prefix('phone')->name('phone.')->group(
                    function () {
                        Route::get('/{userId}', 'PhoneController@index')->name('index');
                    }
                );

                Route::prefix('vehicle')->name('vehicle.')->middleware(
                    'permission:' . \App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_PLAYER_EDIT_VEHICLE
                )->group(
                    function () {
                        Route::get('/{characterId}', 'VehicleController@index')->name('index');
                        Route::get('/edit/{id}', 'VehicleController@edit')->name('edit');
                        Route::post('/edit/{id}', 'VehicleController@save')->name('save');
                        Route::post('/tune/{id}', 'VehicleController@tune')->name('tune');
                        Route::delete('/delete/{id}', 'VehicleController@delete')->name('delete');
                    }
                );

                Route::prefix('bans')->name('bans.')->middleware(
                    'permission:' . \App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_PLAYER_EDIT_BANS
                )->group(
                    function () {
                        Route::get('/create', 'BanController@create')->name('create');
                        Route::get('serverBans/{accountId}', 'BanController@serverBans')->name('serverBans');
                        Route::get('/{accountId}', 'BanController@index')->name('index');
                        Route::post('/save/{accountId}', 'BanController@save')->name('save');
                        Route::delete('/delete/{id}', 'BanController@delete')->name('delete');
                        Route::delete('serverBans/delete/{id}', 'BanController@deleteServerBans')
                            ->name('deleteServerBans');
                    }
                );
                Route::prefix('cashFlow')->name('cashFlow.')->middleware(
                    'permission:' . \App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_PLAYER_EDIT_CASH_FLOW
                )->group(
                    function () {
                        Route::get('/{characterId}', 'CashFlowController@index')->name('index');
                    }
                );

                Route::prefix('callHistory')->name('callHistory.')->middleware(
                    'permission:' . \App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_PLAYER_EDIT_CALL_HISTORY
                )->group(
                    function () {
                        Route::get('/{characterId}', 'CallHistoryController@index')->name('index');
                    }
                );
            }
        );

        Route::prefix('config')->name('config.')->middleware(
            'permission:' . \App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_SETTINGS
        )->group(
            function () {
                Route::get('/', 'ConfigController@index')->name('index');
                Route::post('/', 'ConfigController@save')->name('save');
            }
        );

        Route::prefix('itemList')->name('itemList.')->middleware(
            'permission:' . \App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_ITEM_LIST
        )->group(
            function () {
                Route::get('/', 'ItemListController@index')->name('index');
                Route::get('/search/itemList', 'ItemListController@searchItemList')->name('searchItemList');
                Route::get('/search/vehicles', 'ItemListController@searchVehicles')->name('searchVehicles');
            }
        );

        Route::prefix('code')->name('code.')->middleware(
            'permission:' . \App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_CODE_GENERATOR
        )->group(
            function () {
                Route::get('/', 'CodeController@index')->name('index');
                Route::get('/generate', 'CodeController@generate')->name('generate');
                Route::delete('/delete/{id}', 'CodeController@delete')->name('delete');
            }
        );

        Route::prefix('group')->name('group.')->middleware(
            'permission:' . \App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_GROUP
        )->group(
            function () {
                Route::get('/', 'GroupController@index')->name('index');
                Route::post('/create', 'GroupController@create')->name('create');
                Route::get('/show/{id}', 'GroupController@show')->name('show');
                Route::delete('/delete/{id}', 'GroupController@delete')->name('delete');
            }
        );

        Route::prefix('business')->name('business.')->middleware(
            'permission:' . \App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_BUSINESS
        )->group(
            function () {
                Route::get('/', 'BusinessController@index')->name('index');
                Route::post('/create', 'BusinessController@create')->name('create');
                Route::get('/show/{id}', 'BusinessController@show')->name('show');
                Route::delete('/delete/{id}', 'BusinessController@delete')->name('delete');
            }
        );

        Route::prefix('log')->name('log.')->middleware(
            'permission:' . \App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_LOGS
        )->group(
            function () {
                Route::get('/', 'LogController@index')->name('index');
                Route::get('/show/{id}', 'LogController@show')->name('show');
            }
        );

        Route::prefix('logApi')->name('logApi.')->middleware(
            'permission:' . \App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_LOGS
        )->group(
            function () {
                Route::get('/', 'LogApiController@index')->name('index');
            }
        );

        Route::prefix('killLog')->name('killLog.')->middleware(
            'permission:' . \App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_LOGS
        )->group(
            function () {
                Route::get('/', 'KillLogController@index')->name('index');
            }
        );

        Route::prefix('serverLog')->name('serverLog.')->middleware(
            'permission:' . \App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_LOGS
        )->group(
            function () {
                Route::get('/', 'ServerLogController@index')->name('index');
                Route::get('/reload', 'ServerLogController@reload')->name('reload');
            }
        );

        Route::prefix('permission')->name('permission.')->middleware(
            'permission:' . \App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_PERMISSIONS
        )->group(

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('', 'Auth\RegisterController@showRegistrationForm')->name('index');
Route::get('/wasted', 'IndexController@wasted')->name('wasted');
Auth::routes();

Route::namespace('BugReport')->prefix('bugReport')->name('bugReport.')->group(
    function () {
        Route::get('{hash}', 'IndexController@index')->name('index');
        Route::post('/save/{hash}', 'IndexController@save')->name('save');
    }
);

Route::namespace('Web')->prefix('web')->name('web.')->group(
    function () {
        Route::get('{hash}', 'IndexController@index')->name('index');
        Route::namespace('Marketplace')->prefix('marketplace')->name('marketplace.')->group(
            function () {
                Route::get('{hash}', 'IndexController@index')->name('index');
                Route::get('category/{id}/{hash}', 'IndexController@category')->name('category');
                Route::get('offers/{hash}', 'IndexController@offers')->name('offers');
                Route::get('create/{hash}', 'IndexController@create')->name('create');
                Route::post('{hash}', 'IndexController@save')->name('save');
                Route::delete('{id}/{hash}', 'IndexController@delete')->name('delete');
            }
        );

        Route::namespace('News')->prefix('news')->name('news.')->group(
            function () {
                Route::get('/{hash}', 'IndexController@index')->name('index');
                Route::get('/{categoryId}/{hash}', 'IndexController@category')->name('category');
                Route::get('show/{id}/{hash}', 'IndexController@show')->name('show');
            }
        );

        Route::namespace('Hunt')->prefix('hunt')->name('hunt.')->group(
            function () {
                Route::get('/{hash}', 'IndexController@index')->name('index');
            }
        );

        Route::namespace('Stock')->prefix('stock')->name('stock.')->group(
            function () {
                Route::get('/{hash}', 'IndexController@index')->name('index');
                Route::get('depot/{hash}', 'IndexController@depot')->name('depot');
                Route::get('show/{id}/{hash}', 'IndexController@show')->name('show');
                Route::get('buy/{id}/{hash}', 'IndexController@buy')->name('buy');
                Route::get('sell/{id}/{hash}', 'IndexController@sell')->name('sell');
                Route::post('buy/{id}/{hash}', 'IndexController@buyPost')->name('buyPost');
                Route::post('sell/{id}/{hash}', 'IndexController@sellPost')->name('sellPost');
                Route::get('getStockData/{id}', 'IndexController@getStockData')->name('getStockData');
            }
        );

        Route::namespace('Mail')->prefix('mailbox')->name('mailbox.')->group(
            function () {
                Route::get('index/{hash}', 'MailboxController@index')->name('index');
                Route::get('create/{hash}', 'MailboxController@create')->name('create');
                Route::get('add/{hash}', 'MailboxController@add')->name('add');
                Route::post('save/{hash}', 'MailboxController@save')->name('save');
                Route::post('addSave/{hash}', 'MailboxController@addSave')->name('addSave');
                Route::prefix('mail')->name('mail.')->group(
                    function () {
                        Route::get('index/{webMailAddressId}/{hash}', 'MailController@index')->name('index');
                        Route::get('outgoing/{webMailAddressId}/{hash}', 'MailController@outgoing')->name('outgoing');
                        Route::get('create/{webMailAddressId}/{hash}', 'MailController@create')->name('create');
                        Route::get('reply/{webMailAddressId}/{id}/{hash}', 'MailController@reply')->name('reply');
                        Route::get('share/{webMailAddressId}/{id}/{hash}', 'MailController@share')->name('share');
                        Route::get('show/{webMailAddressId}/{id}/{hash}', 'MailController@show')->name('show');
                        Route::post('save/{webMailAddressId}/{hash}', 'MailController@save')->name('save');
                        Route::delete('delete/{webMailAddressId}/{id}/{hash}', 'MailController@delete')->name('delete');
                    }
                );
            }
        );
        Route::namespace('YellowPage')->prefix('yellowPage')->name('yellowPage.')->group(
            function () {
                Route::get('{hash}', 'IndexController@index')->name('index');
                Route::post('save/{hash}', 'IndexController@save')->name('save');
                Route::get('call/{id}/{hash}', 'IndexController@call')->name('call');
                Route::delete('delete/{hash}', 'IndexController@delete')->name('delete');
            }
        );

        Route::namespace('Social')->prefix('social')->name('social.')->group(
            function () {
                Route::get('{hash}', 'IndexController@index')->name('index');
                Route::get('follow/{hash}', 'IndexController@follow')->name('follow');
                Route::post('retweet/{hash}', 'IndexController@retweet')->name('retweet');
                Route::post('{hash}', 'IndexController@post')->name('post');
            }
        );
        Route::prefix('medic')->name('medic.')->group(
            function () {
                Route::get(
                    '{hash}',
                    function (\Illuminate\Http\Request $request, string $hash) {
                        return view('web.medic.index', ['hash' => $hash]);
                    }
                )->name('index');
            }
        );
        Route::prefix('police')->name('police.')->group(
            function () {
                Route::get(
                    '{hash}',
                    function (\Illuminate\Http\Request $request, string $hash) {
                        return view('web.police.index', ['hash' => $hash]);
                    }
                )->name('index');
            }
        );
    }
);

Route::namespace('DarkWeb')->prefix('darkWeb')->name('darkWeb.')->group(
    function () {
        Route::get('{hash}', 'IndexController@index')->name('index');
        Route::get('weirdImages/{hash}', 'IndexController@weirdImages')->name('weirdImages');
        Route::get('video/{hash}', 'IndexController@video')->name('video');
        Route::get('2048/{hash}', 'IndexController@twoThousandFortyEight')->name('2048');
        Route::get('loading/{hash}', 'IndexController@loading')->name('loading');
        Route::post('save/{hash}', 'IndexController@save')->name('save');
        Route::namespace('DarkBuy')->prefix('darkBuy')->name('darkBuy.')->group(
            function () {
                Route::get('{hash}', 'IndexController@index')->name('index');
                Route::get('category/{category}/{hash}', 'IndexController@category')->name('category');
                Route::get('offers/{hash}', 'IndexController@offers')->name('offers');
                Route::get('create/{hash}', 'IndexController@create')->name('create');
                Route::post('{hash}', 'IndexController@save')->name('save');
                Route::get('pay/{id}/{hash}', 'IndexController@pay')->name('pay');
                Route::get('bought/{hash}', 'IndexController@bought')->name('bought');
                Route::get('call/{id}/{hash}', 'IndexController@call')->name('call');
                Route::delete('{id}/{hash}', 'IndexController@delete')->name('delete');
            }
        );
        Route::namespace('Wallet')->prefix('wallet')->name('wallet.')->group(
            function () {
                Route::get('{hash}', 'IndexController@index')->name('index');
                Route::post('create/{hash}', 'IndexController@create')->name('create');
                Route::get('transactions/{hash}', 'IndexController@transactions')->name('transactions');
                Route::get('transfer/{hash}', 'IndexController@transfer')->name('transfer');
                Route::post('transfer/{hash}', 'IndexController@transferPost')->name('transferPost');
                Route::get('exchange/{hash}', 'IndexController@exchange')->name('exchange');
                Route::post('exchange/{hash}', 'IndexController@exchangePost')->name('exchangePost');
            }
        );
    }
);

Route::namespace('Auth')->middleware('auth')->prefix('auth')->name('auth.')->group(
    function () {
        Route::prefix('account')->name('account.')->group(
            function () {
                Route::get('index', 'AccountController@index')->name('index');
                Route::get('edit', 'AccountController@edit')->name('edit');
                Route::post('save', 'AccountController@save')->name('save');
            }
        );
        Route::prefix('character')->name('character.')->group(
            function () {
                Route::get('index', 'CharacterController@index')->name('index');
                Route::post('save', 'CharacterController@save')->name('save');
            }
        );

        Route::namespace('News')->prefix('news')->name('news.')->middleware(
            'permission:' . \App\Libraries\Permission\Enum\Permission::ACCESS_NEWS
        )->group(
            function () {
                Route::get('index', 'IndexController@index')->name('index');
                Route::get('create', 'IndexController@create')->name('create');
                Route::get('edit/{id}', 'IndexController@edit')->name('edit');
                Route::post('save/{id}', 'IndexController@saveEdit')->name('saveEdit');
                Route::post('save', 'IndexController@save')->name('save');

resources/views/admin/index.blade.php
<?php
/**
 * index.blade.php
 * Copyright (C) Marcel Pfeifer 2019 <webmaster@m-pfeifer.de>
 * Date: 31.08.2019
 * Time: 20:30
 *
 *    ___
 * __/_  `.  .-"""-.
 * \_,` | \-'  /   )`-')
 *  "") `"`    \  ((`"`
 *  ___Y  ,    .'7 /|
 * (_,___/...-` (_/_/
 */

?>
@extends('admin.layout.app')
@section('title')
    Admin Dashboard
@endsection
@section('content')
    Willkommen im Admin Dashboard

    <div id="content"
         data-labels="{{ $labels }}"
         data-ram-max="{{ $ramMax }}"
         data-ram="{{ $ram }}"
         data-cpu="{{ $cpu }}"
         data-altv="{{ $altv }}"
         data-altv-test="{{ $altvTest }}"
         data-ts="{{ $ts }}"
         data-forum="{{ $forum }}">
        <div>
            <h2> Server Status</h2>
            <canvas id="server"></canvas>
        </div>
        <div>
            <h2> RAM Usage </h2>
            <canvas id="ram"></canvas>
        </div>

        <div>
            <h2> CPU Usage </h2>
            <canvas id="cpu"></canvas>
        </div>
    </div>
@endsection

resources/views/admin/sidebar.blade.php
<div class="col-12 col-md-3">
    <div class="card bg-white text-secondary border-primary">
        <div class="card-header bg-primary text-white">
            <i class="fas fa-align-justify"></i>
            Navigation
        </div>
        <div class="card-body text-dark">
            <h4 class="font-italic border-bottom border-primary">Allgemein</h4>
            <ul class="nav flex-column">
                @permission(\App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_PLAYER)
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="{{ route('admin.player.index') }}">
                        <i class="fas fa-user"></i>
                        Spielerübersicht
                    </a>
                </li>
                @endpermission
                @permission(\App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_CODE_GENERATOR)
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="{{ route('admin.code.index') }}">
                        <i class="fas fa-qrcode"></i>
                        Code Generator
                    </a>
                </li>
                @endpermission
                @permission(\App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_GROUP)
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="{{ route('admin.group.index') }}">
                        <i class="fas fa-user-friends"></i>
                        Gruppen
                    </a>
                </li>
                @endpermission
                @permission(\App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_BUSINESS)
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="{{ route('admin.business.index') }}">
                        <i class="fas fa-building"></i>
                        Firmen
                    </a>
                </li>
                @endpermission
                @permission(\App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_VEHICLE_SHOP)
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="{{ route('admin.vehicleShop.index') }}">
                        <i class="fas fa-car"></i>
                        Fahrzeugshop
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="{{ route('admin.vehicleShopUnregistered.index') }}">
                        <i class="fas fa-car"></i>
                        Fahrzeugshop Unregistriert
                    </a>
                </li>
                @endpermission
                @permission(\App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_ITEM_STORE)
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="{{ route('admin.itemStore.index') }}">
                        <i class="fas fa-box"></i>
                        ItemStore
                    </a>
                </li>
                @endpermission
                @permission(\App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_HAPPY_BUY_CATEGORY)
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="{{ route('admin.web.happyBuy.index') }}">
                        <i class="fas fa-folder"></i>
                        Happy Buy Kategorien
                    </a>
                </li>
                @endpermission
                @permission(\App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_ITEM_LIST)
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="{{ route('admin.itemList.index') }}">
                        <i class="fas fa-search"></i>
                        Item- und Fahrzeugsuche
                    </a>
                </li>
                @endpermission
                @permission(\App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_SETTINGS)
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="{{ route('admin.config.index') }}">
                        <i class="fas fa-cog"></i>
                        Einstellungen
                    </a>
                </li>
                @endpermission
                @permission(\App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_PERMISSIONS)
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="{{ route('admin.permission.index') }}">
                        <i class="fas fa-balance-scale-right"></i>
                        Rechte Managment
                    </a>
                </li>
                @endpermission
                @permission(\App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_REPORT)
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="{{ route('admin.report.index') }}">
                        <i class="fas fa-bug"></i>
                        Reportübersicht
                    </a>
                </li>
                @endpermission
                @permission(\App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_BUG_REPORT)
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="{{ route('admin.bugReport.index') }}">
                        <i class="fas fa-bug"></i>
                        Bug-Report Übersicht
                    </a>
                </li>
                @endpermission

                @permission(\App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_BAN)
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="{{ route('admin.ban.index') }}">
                        <i class="fas fa-ban"></i>
                        Ban-Management
                    </a>
                </li>
                @endpermission

                @permission(\App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_LOGS)
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="{{ route('admin.log.index') }}">
                        <i class="fas fa-clipboard"></i>
                        Log-Einträge
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="{{ route('admin.logApi.index') }}">
                        <i class="fas fa-clipboard"></i>
                        API Log-Einträge
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="{{ route('admin.serverLog.index') }}">
                        <i class="fas fa-clipboard"></i>
                        Server Log-Einträge
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="{{ route('admin.killLog.index') }}">
                        <i class="fas fa-clipboard"></i>
                        Kill Log-Einträge
                    </a>
                </li>
                @endpermission

                @permission(\App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_STOCK)
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="{{ route('admin.stock.index') }}">
                        <i class="fas fa-coins"></i>
                        Börse
                    </a>
                </li>
                @endpermission

                @permission(\App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_WHITELIST_QUESTION)
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="{{ route('admin.whitelistQuestion.index') }}">
                        <i class="fas fa-question"></i>
                        Whitelist Fragen
                    </a>
                </li>
                @endpermission
            </ul>

            <h4 class="font-italic border-bottom border-primary">Supportformulare</h4>
            <ul class="nav flex-column">
                @permission(\App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_SUPPORT_FORM_WHITELIST)
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="{{ route('admin.supportForm.whitelist.index') }}">
                        <i class="fab fa-wpforms"></i>
                        Whitelist
                    </a>
                </li>
                @endpermission
                @permission(\App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_SUPPORT_FORM_TECHNICAL_FAQ)
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="{{ route('admin.supportForm.technicalFaq.index') }}">
                        <i class="fab fa-wpforms"></i>
                        Technisches FAQ
                    </a>
                </li>
                @endpermission
                @permission(\App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_SUPPORT_FORM_REFUND)
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="{{ route('admin.supportForm.refund.index') }}">
                        <i class="fab fa-wpforms"></i>
                        Erstattung
                    </a>
                </li>
                @endpermission
                @permission(\App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_SUPPORT_FORM_INFRINGEMENT)
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="{{ route('admin.supportForm.infringement.index') }}">
                        <i class="fab fa-wpforms"></i>
                        Regelverstoß
                    </a>
                </li>
                @endpermission
                @permission(\App\Libraries\Permission\Enum\Permission::ACCESS_BACKEND_SUPPORT_FORM_BANS)
                <li class="nav-item">
                    <a class="nav-link text-secondary" href="{{ route('admin.supportForm.ban.index') }}">
                        <i class="fab fa-wpforms"></i>
                        Bans
                    </a>
                </li>
                @endpermission
            </ul>
            @permission(\App\Libraries\Permission\Enum\Permission::ACCESS_API)
            <div class="row mt-1 border-top border-primary">
                <div class="col-12 mt-1 text-center">
                    <a class="btn text-center btn-dark" href="{{ route('api.index') }}">Zur API</a>
                </div>
            </div>
            @endpermission
        </div>
    </div>
</div>